# Minimal Jekyll config for GitHub Pages
title: Senioren-IT Kurs
description: Info-Website für den Senioren-IT Kurs – Termine, Materialien und Kontakt.
baseurl: "/senioren-it-kurs" # Projektname für GitHub Pages
url: "https://gkoe.github.io" # passe ggf. an oder lasse leer
# theme: minima  # Auskommentiert, um eigenes Design zu verwenden
markdown: kramdown
permalink: /:title/
